import { stripTypeScriptTypes } from "node:module";
import { runInNewContext } from "node:vm";
import {
  getTableConfig,
  integer,
  real,
  type SQLiteTable,
  sqliteTable,
  text,
} from "drizzle-orm/sqlite-core";
import { describe, expect, it } from "vitest";
import {
  type CollectionConfig,
  type ContentConfig,
  contentConfigToSchema,
  generateSchemaSource,
} from "../../src/core/content/index.js";
import { LouiseContentError } from "../../src/core/errors.js";

// `generateSchemaSource` in core/content/schema-gen.ts (#695): the Drizzle
// schema file a site generates from its ContentConfig. Asserts on the emitted
// text, then evaluates it and checks that every table matches what codegen.ts
// builds at runtime from the same config, since the two are separate switches
// kept in sync by hand.

const moment = new Date("2026-01-02T03:04:05.000Z");

const articles: CollectionConfig = {
  slug: "articles",
  fields: {
    id: { type: "number", autoIncrement: true },
    title: { type: "text", required: true, unique: true, defaultValue: "Untitled" },
    heroImage: { type: "upload", name: "hero" },
    body: { type: "richText", required: true, defaultValue: { type: "doc" } },
    blocks: { type: "array", fields: { kind: { type: "text" } } },
    meta: { type: "json", defaultValue: { tags: ["news"] } },
    author: { type: "relationship", relationTo: "people", required: true },
    tags: { type: "relationship", relationTo: "tags", hasMany: true },
    status: {
      type: "select",
      options: ["draft", "live"],
      required: true,
      defaultValue: "draft",
    },
    rating: { type: "number", required: true, defaultValue: 3 },
    score: { type: "number" },
    createdAt: { type: "date", defaultValue: "now", required: true },
    updatedAt: { type: "date", mode: "timestamp_ms", defaultValue: moment, onUpdate: "now" },
    reviewedAt: { type: "date" },
    address: {
      type: "group",
      fields: {
        city: { type: "text" },
        geo: { type: "group", fields: { lat: { type: "number" } } },
      },
    },
  },
  versions: { drafts: true },
};

const people: CollectionConfig = {
  slug: "people",
  fields: {
    id: { type: "number", autoIncrement: true },
    name: { type: "text", required: true },
  },
};

const config: ContentConfig = { collections: [articles, people] };

/** Evaluates generated schema source into its exported tables. */
function evaluate(source: string): Record<string, SQLiteTable> {
  const js = stripTypeScriptTypes(source)
    .replace(/^import .*$/gm, "")
    .replace(/^export const (\w+) =/gm, "exports.$1 =");
  const exports: Record<string, SQLiteTable> = {};
  runInNewContext(js, { exports, integer, real, sqliteTable, text });
  return exports;
}

/** The parts of a table's shape both generators are responsible for. */
function shape(table: SQLiteTable) {
  const { name, columns } = getTableConfig(table);
  return {
    name,
    columns: columns
      .map((column) => ({
        name: column.name,
        sqlType: column.getSQLType(),
        columnType: column.columnType,
        notNull: column.notNull,
        primary: column.primary,
        unique: column.isUnique,
        hasDefault: column.hasDefault,
        default: column.default,
        enumValues: column.enumValues,
        hasDefaultFn: typeof column.defaultFn === "function",
        hasOnUpdateFn: typeof column.onUpdateFn === "function",
      }))
      .sort((a, b) => a.name.localeCompare(b.name)),
  };
}

describe("generateSchemaSource", () => {
  const source = generateSchemaSource(config);

  it("opens with the generated-file banner and sorted, minimal imports", () => {
    const lines = source.split("\n");
    expect(lines[0]).toBe("// Generated by louise-toolkit/content — do not hand-edit.");
    expect(lines[1]).toBe("// Source: this app's ContentConfig (see defineContentConfig).");
    expect(lines[2]).toBe('import type { JsonValue } from "louise-toolkit/content";');
    expect(lines[3]).toBe(
      'import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";',
    );
    expect(source.endsWith("});\n")).toBe(true);
  });

  it("emits each field type's column builder chain", () => {
    expect(source).toContain('  id: integer("id").primaryKey({ autoIncrement: true }),');
    expect(source).toContain('  title: text("title").notNull().unique().default("Untitled"),');
    // `name` overrides the column; the key stays the property name.
    expect(source).toContain('  heroImage: text("hero"),');
    expect(source).toContain(
      '  body: text("body", { mode: "json" }).$type<JsonValue>().notNull().default({"type":"doc"}),',
    );
    expect(source).toContain('  blocks: text("blocks", { mode: "json" }).$type<JsonValue>(),');
    expect(source).toContain(
      '  meta: text("meta", { mode: "json" }).$type<JsonValue>().default({"tags":["news"]}),',
    );
    expect(source).toContain('  author: integer("author").notNull(),');
    expect(source).toContain(
      '  status: text("status", { enum: ["draft", "live"] }).notNull().default("draft"),',
    );
    expect(source).toContain('  rating: real("rating").notNull().default(3),');
    expect(source).toContain('  score: real("score"),');
    expect(source).toContain(
      '  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),',
    );
    expect(source).toContain(
      `  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).$defaultFn(() => new Date(${moment.getTime()})).$onUpdateFn(() => new Date()),`,
    );
    expect(source).toContain('  reviewedAt: integer("reviewed_at", { mode: "timestamp" }),');
  });

  it("flattens group fields into prefixed columns, recursively", () => {
    expect(source).toContain('  address_city: text("address_city"),');
    expect(source).toContain('  address_geo_lat: real("address_geo_lat"),');
    expect(source).not.toContain("address:");
  });

  it("moves a hasMany relationship to a join table instead of a column", () => {
    expect(source).not.toMatch(/^ {2}tags:/m);
    expect(source).toContain(
      'export const articles_tags = sqliteTable("articles_tags", {\n' +
        '  articles_id: integer("articles_id").notNull(),\n' +
        '  tags_id: integer("tags_id").notNull(),\n' +
        "});",
    );
  });

  it("adds the version pointer and a versions table only for a drafts collection", () => {
    expect(source).toContain('  publishedVersionId: integer("published_version_id"),');
    expect(source).toContain('export const articles_versions = sqliteTable("articles_versions", {');
    expect(source).not.toContain("people_versions");
    const peopleBlock = source.slice(source.indexOf("export const people"));
    expect(peopleBlock).not.toContain("publishedVersionId");
  });

  it("adds the provenance columns codegen adds, when the collection records provenance", () => {
    const tracked = {
      collections: [{ ...articles, versions: { drafts: true, provenance: true } }],
    };
    const text = generateSchemaSource(tracked);
    expect(text).toContain('  author: text("author"),\n');
    expect(text).toContain(
      '  source: text("source", { enum: ["editor", "realtime", "agent"] }),\n',
    );
    expect(source).not.toContain('text("author")');
    const generated = evaluate(text);
    const runtime = contentConfigToSchema(tracked);
    expect(shape(generated.articles_versions)).toEqual(shape(runtime.articles_versions));
  });

  it("builds the same tables codegen builds at runtime", () => {
    const generated = evaluate(source);
    const runtime = contentConfigToSchema(config);
    expect(Object.keys(generated).sort()).toEqual(Object.keys(runtime).sort());
    for (const [name, table] of Object.entries(runtime)) {
      expect(shape(generated[name]), name).toEqual(shape(table));
    }
  });

  it("keeps the fixed date default as the configured instant", () => {
    const { columns } = getTableConfig(evaluate(source).articles);
    const updatedAt = columns.find((column) => column.name === "updated_at");
    expect((updatedAt?.defaultFn?.() as Date).getTime()).toBe(moment.getTime());
  });

  it("omits excluded collections and every table they own", () => {
    const only = generateSchemaSource(config, { exclude: ["articles"] });
    expect(only).not.toContain("articles");
    expect(only).toContain('export const people = sqliteTable("people", {');
    expect(Object.keys(evaluate(only))).toEqual(["people"]);
  });

  it("skips the JsonValue import and unused builders when no column needs them", () => {
    const only = generateSchemaSource(config, { exclude: ["articles"] });
    expect(only).not.toContain("JsonValue");
    expect(only).toContain('import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";');
    expect(only).not.toContain("real");
  });

  it("emits only the table builder for a config with no collections", () => {
    const empty = generateSchemaSource({ collections: [] });
    expect(empty).toContain('import { sqliteTable } from "drizzle-orm/sqlite-core";');
    expect(evaluate(empty)).toEqual({});
  });

  it("rejects a field type it has no column mapping for", () => {
    const bogus = {
      collections: [{ slug: "things", fields: { x: { type: "bogus" } } }],
    } as unknown as ContentConfig;
    expect(() => generateSchemaSource(bogus)).toThrow(LouiseContentError);
    expect(() => generateSchemaSource(bogus)).toThrow(
      'Field type "bogus" is not yet supported by louise-toolkit/content schema-gen',
    );
  });
});
